pipeline {
    agent any
    tools {
        maven 'maven381' 
    }
    stages {
            stage('clean up') {
            steps {
                deleteDir()
            }
        }
        stage('git clone') {
            steps {
                echo 'Hello World'
                sh 'git clone https://github.com/Thumma123/simple-java-maven-app'
            }
        }
        stage('mvn version') {
            steps {
                sh 'mvn --version'
            }
        }
        stage('mvn test') {
            steps {
                dir("simple-java-maven-app"){
                sh 'mvn test'
                }
            }
        }
    }
}

