pipeline {
    agent any
    tools {
        maven 'maven381' 
    }
    stages {
        stage('maven test') {
            steps {
                sh 'mvn test'
            }
        }
        stage('mvn build') {
            steps {
                sh 'mvn build'
                }
            }
        }
    }


